### ISSUE TITLE
Secrets.dart file is missing

### ISSUE THREAD

**Issue by Shubxam** [Vulfpeck/fritter_for_reddit#1]
Either this file is missing or I'm unable to find it

**Comment by SarcasticNoodle** [comment]
You need to add your own Secrets.dart file and supply your own API KEY.

**Comment by Vulfpeck** [comment]
You need to get your own API Key by adding your app to your reddit prefs. Refer to Getting Started section here https://github.com/reddit-archive/reddit/wiki/oauth2

**Comment by Shubxam** [comment]
Alright, thanks for help!
