### ISSUE TITLE
Got bad request When trying to log in

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Vulfpeck/fritter_for_reddit#3]
![Screenshot_20200306-153746_Chrome](https://user-images.githubusercontent.com/23037821/76130787-efd08080-5fc0-11ea-998b-36fae305a338.jpg)
Could this have to do with the application secret?

**Comment by ThinkDigitalSoftware** [comment]
Turns out you need to set the redirect url as http://localhost:8080/ Can you indicate that in the readme?

**Comment by Vulfpeck** [comment]
Thank you for letting me know!

**Comment by ThinkDigitalSoftware** [comment]
No problem

**Comment by debpalash** [comment]
> Turns out you need to set the redirect url as http://localhost:8080/ Can you indicate that in the readme?

So, this fixed yet? I'm also having same problem.

**Comment by Vulfpeck** [comment]
I've added this specific point to the readme for now. Signing in works fine for me. Double check your redirect url and ensure that you've added the correct client_id in secrets.dart

**Comment by ThinkDigitalSoftware** [comment]
> > Turns out you need to set the redirect url as http://localhost:8080/ Can you indicate that in the readme?
> 
> So, this fixed yet? I'm also having same problem.

It's not an issue, it just a step that needs to be done
